"""crear tablas iniciales

Revision ID: 59c3af2bc5bc
Revises: 
Create Date: 2026-10-06 18:20:12.553373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c3af2bc5bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_incidentes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('umbral_sensibilidad', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=250), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'conductor', 'supervisor', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('numero_licencia', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_vinculacion', sa.Date(), nullable=True),
    sa.CheckConstraint("(rol = 'conductor' AND numero_licencia IS NOT NULL AND fecha_vinculacion IS NOT NULL) OR (rol <> 'conductor')", name='ck_usuario_campos_conductor'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('numero_licencia')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo_vehiculo', sa.Enum('bus', 'camion_carga', name='tipovehiculoenum'), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'mantenimiento', 'inactivo', name='estadovehiculoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conductor_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'finalizada', name='estadosesionenum'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sesion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_incidente_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('duracion_segundos', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('severidad', sa.Enum('baja', 'media', 'alta', name='severidadenum'), nullable=False),
    sa.Column('valor_metrica', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('comentario_conductor', sa.Text(), nullable=True),
    sa.Column('revisado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_incidente_id'], ['tipos_incidentes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('sesiones')
    op.drop_table('vehiculos')
    op.drop_table('usuarios')
    op.drop_table('tipos_incidentes')
    # ### end Alembic commands ###
